---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: loginpage-htpasswd
  namespace: loginpage
spec:
  encryptedData:
    .htpasswd: AgAXBrcYjo/Ou5rIXKGHnDOLzoT6FgVYjV2yoUp81TEmJHy+WQhKLMJezdPaKosEujPUMZPHfy41RYX50LPw7OcJqGXaFwZlFqwnSI1ItPbMdsw/GZU8WVbuLs2GD6NnLqHlRnTruwA10p6UYsX5Tp4uSoZ/xgV9IAS2+jP+OlLmoxEJdKNxS/p6BPBu2SbT8hrg1g/+BZHiDwrO8D0D3OHhrhRsMmAsSWH3a65Q7Mo8BIggHG71NKLLS7F5tOouZY/S9M9QW+UMhJg8FnmbQmQaBE/s28d2Eq4d2JwO9NVO+LQIPbQWuD+uwJylQ9Chb0RjEtwlTqgI0eFia3Iuq/Tp1PWomR6lm5Tpd9TLhH6MczPqAyG43kK2URaj7m8lHpNqSCKodVsl5p8HqvCSZBerlEcksK6gxMdvqiCvmzHtVLjjklH20RzwMvaAwhUn4sqjHQQo4vcqxWukjis76z1XolaZuAkO28HBXTwuVzXlUDW6FoBTJrVNgE7dXmLQJr8NRCrRXFtqSV1eLEiADFCZKVNVJlK6CbalP5rg9a2HTNK02ZpaOKDfXHPWHZEaaL29hg9Cwk2uW/W3l+Sv/xiTozcXY4JG6TXnbu/Xw1Kp4sCxiFQoXeAIhP/DmZt+XVt2lBwCC3OVkuM7EYZhFr0bz1vBGGQzJs/t9HeD6j0pJN6ma9kHVTNPk7VY4mx7RUW6yzyQExOfEPIBS4kemjcdARi9Fj8PUYXCtbwiZmooPBkb/kemHwc9aDpVVQ==
  template:
    metadata:
      name: loginpage-htpasswd
      namespace: loginpage
