apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ include "canary-demo.fullname" . }}
  labels:
    {{- include "canary-demo.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      {{- include "canary-demo.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "canary-demo.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: canary-demo
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
  strategy:
    canary:
      # stable = current/majority version. canary = the new version getting
      # a growing slice of replicas. Both let you curl each version directly.
      stableService: {{ include "canary-demo.fullname" . }}-stable
      canaryService: {{ include "canary-demo.fullname" . }}-canary
      steps:
        {{- toYaml .Values.canary.steps | nindent 8 }}
