apiVersion: v1
kind: Service
metadata:
  name: {{ include "canary-demo.fullname" . }}-stable
  labels:
    {{- include "canary-demo.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  # Selector is managed by the Rollout controller - always points at the
  # last fully-promoted ("stable") ReplicaSet, never the in-progress canary.
  selector:
    {{- include "canary-demo.selectorLabels" . | nindent 4 }}
