apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bluegreen-demo
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: https://github.com/harrylog/argocd-octopus-1.git
    targetRevision: main
    path: charts/bluegreen-demo
    helm:
      valueFiles:
        - values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: bluegreen-demo

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
